apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: myapp
        image: hoangguruu/myapp-private:10
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000 # The port that the container is running on in the cluster
